// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	IsCompleted bool               `json:"is_completed"`
	IsDeleted   bool               `json:"is_deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
